config/routes.rb
Rails.application.routes.draw do

  root 'chatroom#index'
  get 'login', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular grey beer icon"></i>
  Say Something
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui feed">
          <div class="event">
            <div class="content">
              <div class="summary">
                 <a>Elliot Fu</a> added <a>Jenny Hess</a> as a friend
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                 <a>Stevie Feliciano</a> added <a>Elliot Fu</a> as a friend
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                 <a>Helen Troy</a> added <a>Christian Rocha</a> as a friend
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
                 <em>Christian Rocha</em>: Test message
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="extra content">
        <form class="ui reply form">
          <div class="field">
            <div class="ui fluid icon input">
              <input type="text" placeholder="Enter a message...">
              <i class="bordered inverted grey edit icon"></i>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted grey vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_menu.html.erb
<div class="ui large borderless grey inverted menu my-menu">
  <div class="ui container">
    <%= link_to 'Chatroom', root_path, class: "item" %>
    <%= link_to 'Messages', root_path, class: "item" %>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item">Log out</a>
          <%= link_to 'Login', login_path, class: "item" %>
          <a class="item">Sign up</a>
        </div>
      </div>
      <div class="item">
          <div class="ui darkslategrey button">Sign Up</div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>